#!/usr/bin/env python3
"""Print a starter B-UML domain model template.

Usage:
    python scaffold_model.py [ClassName ...]

Examples:
    python scaffold_model.py Book Author
    python scaffold_model.py Library Book Author Genre

The output is ready-to-run Python that builds a DomainModel with the given
classes plus one example attribute per class. Edit it, add associations,
and feed it to a generator. The script does not import besser — it just
prints code, so you can run it before installing BESSER.
"""

import sys
import textwrap


HEADER = textwrap.dedent('''\
    """Generated by besser-user/scripts/scaffold_model.py — edit me."""

    from besser.BUML.metamodel.structural import (
        DomainModel, Class, Property, Multiplicity,
        BinaryAssociation,
        StringType, IntegerType, FloatType, BooleanType,
        DateType, DateTimeType,
    )

''')


CLASS_TEMPLATE = textwrap.dedent('''\
    # ----- {class_name} -----
    {var}_name = Property(name="name", type=StringType)
    {var}_id   = Property(name="id",   type=IntegerType, is_id=True)
    {var} = Class(
        name="{class_name}",
        attributes={{{var}_name, {var}_id}},
    )

''')


FOOTER_TEMPLATE = textwrap.dedent('''\
    # ----- Associations -----
    # Example: a 1..* relationship between {first} and {second}
    # Uncomment and adapt:
    # {first}_to_{second} = Property(
    #     name="{second}s", type={second_var},
    #     multiplicity=Multiplicity(0, "*"),
    # )
    # {second}_to_{first} = Property(
    #     name="{first_lower}", type={first_var},
    #     multiplicity=Multiplicity(1, 1),
    # )
    # {first_lower}_{second_lower}_assoc = BinaryAssociation(
    #     name="{first_lower}_{second_lower}",
    #     ends={{{first}_to_{second}, {second}_to_{first}}},
    # )

    # ----- DomainModel -----
    model = DomainModel(
        name="{model_name}",
        types={{{class_set}}},
        # associations={{...}},
        # generalizations={{...}},
    )

    result = model.validate()
    if not result["success"]:
        print("Validation errors:", result["errors"])
        raise SystemExit(1)
    print("Model OK:", model.name)

    # Pick a generator (see besser-generators skill for the full menu):
    # from besser.generators.python_classes import PythonGenerator
    # PythonGenerator(model=model, output_dir="./output").generate()
''')


def to_var(name: str) -> str:
    """Convert PascalCase or other → snake_case variable name."""
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and (name[i - 1].islower() or
                                       (i + 1 < len(name) and name[i + 1].islower())):
            out.append("_")
        out.append(ch.lower())
    return "".join(out).strip("_") or "cls"


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: scaffold_model.py ClassName [ClassName ...]", file=sys.stderr)
        return 2

    classes = argv
    vars_ = [to_var(c) for c in classes]
    model_name = "_".join(classes) + "_model" if len(classes) <= 3 else "domain_model"

    print(HEADER, end="")
    for class_name, var in zip(classes, vars_):
        print(CLASS_TEMPLATE.format(class_name=class_name, var=var), end="")

    if len(classes) >= 2:
        first, second = classes[0], classes[1]
        first_var, second_var = vars_[0], vars_[1]
        footer = FOOTER_TEMPLATE.format(
            first=first, second=second,
            first_var=first_var, second_var=second_var,
            first_lower=first.lower(), second_lower=second.lower(),
            model_name=model_name,
            class_set=", ".join(vars_),
        )
    else:
        footer = textwrap.dedent(f'''\
            # ----- DomainModel -----
            model = DomainModel(
                name="{model_name}",
                types={{{", ".join(vars_)}}},
            )

            assert model.validate()["success"]
            print("Model OK:", model.name)
        ''')

    print(footer, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
