#!/usr/bin/env python3
"""Scaffold a new BESSER generator package.

Usage:
    python scaffold_generator.py <generator_name> <BESSER_repo_root>

Example:
    python scaffold_generator.py graphql ~/code/BESSER

Creates:
    <repo>/besser/generators/<name>/__init__.py
    <repo>/besser/generators/<name>/<name>_generator.py
    <repo>/besser/generators/<name>/templates/<name>_template.py.j2
    <repo>/tests/generators/<name>/test_<name>_generator.py

After scaffolding you still need to:
    1. Implement the actual generation logic in the generator class.
    2. Fill in the Jinja template with your output structure.
    3. Register the generator in
       besser/utilities/web_modeling_editor/backend/config/generators.py
       (SUPPORTED_GENERATORS + get_filename_for_generator).
    4. Add docs in docs/source/generators/<name>.rst and link from
       docs/source/generators.rst.

The scaffold is intentionally minimal — it gives you a working stub that
emits a placeholder file. Run the generated test to confirm wiring before
you add real logic.
"""

from __future__ import annotations

import sys
from pathlib import Path
import textwrap


def class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_")) + "Generator"


def write(path: Path, content: str) -> None:
    if path.exists():
        print(f"skip (exists): {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote: {path}")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    name, repo_root = argv
    name = name.lower().replace("-", "_")
    repo = Path(repo_root).expanduser().resolve()
    if not (repo / "besser" / "generators").is_dir():
        print(f"error: {repo} does not look like a BESSER repo "
              f"(missing besser/generators/)", file=sys.stderr)
        return 1

    cls = class_name(name)
    pkg = repo / "besser" / "generators" / name
    tests = repo / "tests" / "generators" / name

    init_py = textwrap.dedent(f'''\
        from .{name}_generator import {cls}

        __all__ = ["{cls}"]
    ''')

    generator_py = textwrap.dedent(f'''\
        """{cls} — generates output from a BESSER B-UML model.

        TODO: replace this docstring with a real description of what the
        generator produces and which kinds of B-UML models it expects.
        """

        import os
        from jinja2 import Environment, FileSystemLoader

        from besser.generators import GeneratorInterface


        class {cls}(GeneratorInterface):
            """Generator scaffolded by besser-dev/scripts/scaffold_generator.py."""

            def __init__(self, model, output_dir: str | None = None):
                super().__init__(model, output_dir)

            def generate(self) -> None:
                templates_path = os.path.join(os.path.dirname(__file__), "templates")
                env = Environment(
                    loader=FileSystemLoader(templates_path),
                    trim_blocks=True,
                    lstrip_blocks=True,
                )
                template = env.get_template("{name}_template.py.j2")
                output = template.render(
                    classes=self.model.get_classes(),
                    associations=self.model.associations,
                )
                file_path = self.build_generation_path("{name}_output.py")
                with open(file_path, "w", encoding="utf-8") as fh:
                    fh.write(output)
    ''')

    template_jinja = textwrap.dedent('''\
        {# Generated by BESSER {cls} — placeholder template #}
        # Generated by BESSER {cls}
        {% for cls in classes %}
        class {{ cls.name }}:
            {% for attr in cls.attributes %}
            {{ attr.name }}: {{ attr.type.name }}
            {% else %}
            pass
            {% endfor %}

        {% endfor %}
    ''').replace("{cls}", cls)

    test_py = textwrap.dedent(f'''\
        """Smoke tests for {cls}."""

        import os
        import pytest

        from besser.BUML.metamodel.structural import (
            DomainModel, Class, Property, StringType, IntegerType,
        )
        from besser.generators.{name} import {cls}


        @pytest.fixture
        def domain_model():
            name_prop = Property(name="name", type=StringType)
            age_prop = Property(name="age", type=IntegerType)
            person = Class(name="Person", attributes={{name_prop, age_prop}})
            return DomainModel(name="TestModel", types={{person}})


        def test_generates_output_file(domain_model, tmp_path):
            gen = {cls}(model=domain_model, output_dir=str(tmp_path))
            gen.generate()
            assert os.path.exists(tmp_path / "{name}_output.py")


        def test_output_contains_class_name(domain_model, tmp_path):
            gen = {cls}(model=domain_model, output_dir=str(tmp_path))
            gen.generate()
            content = (tmp_path / "{name}_output.py").read_text()
            assert "Person" in content
            assert "name" in content
            assert "age" in content
    ''')

    write(pkg / "__init__.py", init_py)
    write(pkg / f"{name}_generator.py", generator_py)
    write(pkg / "templates" / f"{name}_template.py.j2", template_jinja)
    write(tests / "__init__.py", "")
    write(tests / f"test_{name}_generator.py", test_py)

    print()
    print(f"Scaffolded {cls}. Next steps:")
    print(f"  1) python -m pytest tests/generators/{name}/  # confirm scaffold runs")
    print(f"  2) Implement real logic in besser/generators/{name}/{name}_generator.py")
    print(f"  3) Register in besser/utilities/web_modeling_editor/backend/config/generators.py")
    print(f"  4) Add docs in docs/source/generators/{name}.rst")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
